server:
  port: 8001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway-webflux
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: GlobalFilter
              args:
                baseMessage: SCG Webflux Global filter
                preLogger: true
                postLogger: true
          routes:
            - id: first-service
              uri: lb://FIRST-SERVICE
              predicates:
                - Path=/first-service/**
              filters:
#                - AddRequestHeader=f-request, 1st-request-header-by-yml
#                - AddResponseHeader=f-response, 1st-response-header-by-yml
                - CustomFilter
            - id: second-service
              uri: lb://SECOND-SERVICE
              predicates:
                - Path=/second-service/**
              filters:
#                - AddRequestHeader=s-request, 2nd-request-header-by-yml
#                - AddResponseHeader=s-response, 2nd-response-header-by-yml
                - name: CustomFilter
                - name: LoggingFilter
                  args:
                    baseMessage: SCG Webflux Logging filter
                    preLogger: true
                    postLogger: true